/** @format */

export const ADD_VACATION_REQ = "ADD_VACATION_REQ";
export const UPDATE_PERSONAL_DATA = "UPDATE_PERSONAL_DATA";
export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const REMOVE_TEAM_MEMBER = "REMOVE_TEAM_MEMBER";
